# Argo CD 기본 프로젝트. "Application referencing project default which does not exist" 에러 시 적용.
# 적용: kubectl apply -f argocd/default-project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  description: Default project (all repos, all namespaces)
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: "*"
    - group: "*.io"
      kind: "*"
  namespaceResourceWhitelist:
    - group: ""
      kind: "*"
    - group: "*.io"
      kind: "*"
